import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

// DEV ONLY: Auto-inject auth tokens from production via ?inject_auth=<base64> param.
// Generated by the bookmarklet at public/dev-bookmarklet.html
if (process.env.NODE_ENV === 'development') {
  const params = new URLSearchParams(window.location.search);
  const inject = params.get('inject_auth');
  if (inject) {
    try {
      const data: Record<string, string> = JSON.parse(atob(inject));
      Object.entries(data).forEach(([k, v]) => localStorage.setItem(k, v));
      console.info('[dev] Injected auth tokens from production:', Object.keys(data));
    } catch (e) {
      console.warn('[dev] Failed to parse inject_auth param', e);
    }
    params.delete('inject_auth');
    const clean = window.location.pathname + (params.toString() ? '?' + params.toString() : '');
    window.history.replaceState({}, '', clean);
  }
}

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
